# Read the Docs configuration file
version: 2

# Build env
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Docs configurations
sphinx:
   configuration: docs/source/conf.py

# Output formats
formats:
  - htmlzip
  - pdf

# Requirements
python:
   install:
   - requirements: ./reqs.txt
